#!/bin/bash

echo "Creating a fstab backup..."
sudo cp /etc/fstab /etc/fstab_backup

echo "Removing ceph references from fstab..."
sudo sed -i '/\/var\/lib\/ceph\/osd\//d' /etc/fstab

echo "Getting folders name..."
FOLDER_PATH="/etc/kolla/"
for dir in $FOLDER_PATH*; do
    if [ "$dir" == "$FOLDER_PATH""passwords.yml" ] || \
       [ "$dir" == "$FOLDER_PATH""globals.yml" ] || \
       [ "$dir" == "$FOLDER_PATH""kolla-build.conf" ] || \
       [ "$dir" == "$FOLDER_PATH""config" ]; then
        echo "Skipping:" $dir
    else
        rm -rfv $dir
    fi
done
