---
- name: install python pip
  yum:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "epel-release"
    - "python-pip"
    - "python-devel"
    - "libffi-devel"
    - "gcc"
    - "openssl-devel"
    - "git"
    - "python-docker-py"

- name: upgrade setuptools
  pip:
    name: setuptools
    version: 33.1.1

- name: upgrade pip
  pip:
    name: pip
    state: latest

- name: install ansible 1.9.6,on local host
  pip:
    name: ansible
    version: 1.9.6
  delegate_to: localhost
