---
- name: install systemd device-mapper libseccomp
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "systemd"
    - "device-mapper"
    - "libseccomp"

- name: upgrade docker
  copy:
    src: "{{ item }}"
    dest: "/usr/bin/{{ item }}"
    mode: "0755"
  with_items:
    - "docker"
    - "docker-containerd-current"
    - "docker-containerd-shim-current"
    - "docker-current"
    - "dockerd-current"
    - "docker-containerd"
    - "docker-containerd-shim"
    - "docker-ctr-current"
    - "dockerd"
    - "docker-storage-setup"

- name: upgrade docker config files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/sysconfig/{{ item }}"
    mode: "0755"
  with_items:
    - "docker"
    - "docker-network"
    - "docker-storage"
    - "docker-storage-setup"

- name: create /etc/docker dir
  file:
    state: directory
    path: /etc/docker

- name: copy daemon.json to /etc/docker
  template:
    src: "{{ item }}.j2"
    dest: "/etc/docker/{{ item }}"
  with_items:
    - "daemon.json"

- name: create /usr/libexec/docker dir
  file:
    state: directory
    path: /usr/libexec/docker

- name: copy libexec/docker files to /usr/lib/exec/docker
  copy:
    src: "{{ item }}"
    dest: "/usr/libexec/docker/{{ item }}"
    mode: "0755"
  with_items:
    - "docker-proxy-current"
    - "docker-runc-current"

- name: upgrade docker service file
  template:
    src: "{{ item }}.j2"
    dest: "/usr/lib/systemd/system/{{ item }}"
  with_items:
    - "docker.service"
    - "docker-cleanup.service"
    - "docker-storage-setup.service"
    - "docker-cleanup.timer"

- name: reload systemctl daemon
  command: systemctl daemon-reload

- name: enable and restart docker service
  service:
    name: "docker"
    state: "restarted"
    enabled: "yes"
