---

- name: make sure docker engine is not installed
  yum:
    name: docker-engine
    state: absent

- name: copy docker rpm to /tmp
  copy:
    src: docker-engine-1.13.1-1.el7.centos.x86_64.rpm
    dest: /tmp/docker-engine-1.13.1-1.el7.centos.x86_64.rpm

- name: install docker
  shell: yum install -y /tmp/docker-engine-1.13.1-1.el7.centos.x86_64.rpm

- name: modify service file
  template:
    src: docker.service.j2
    dest: /usr/lib/systemd/system/docker.service

- name: reload systemctl daemon
  command: systemctl daemon-reload

- name: enable and restart docker service
  service:
    name: "docker"
    state: "restarted"
    enabled: "yes"
