---

- include: chyum.yml

- include: install_docker.yml

- include: install_python.yml

- include: bootstrap.yml

- include: build_base.yml
  delegate_to: localhost

- include:  build_kolla_toolbox.yml
  delegate_to: localhost

- include: build_kolla_toolbox.yml
  delegate_to: localhost

- include: start.yml
