---
# Due to the way we do our inventory, ansible does not pick up on the fact that
# this role has already run. We can track what has run with host facts.
common_run: False

####################
# Docker
####################
ansible_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-kolla-toolbox"
ansible_tag: "{{ openstack_release }}"
ansible_image_full: "{{ ansible_image }}:{{ ansible_tag }}"
