---
# The options is config of ceph'

# The "temp" files that are created before merge need to stay persistent due
# to the fact that ansible will register a "change" if it has to create them
# again. Persistent files allow for idempotency
node_templates_directory: "/usr/share/kolla/templates"
container_config_directory: "/var/lib/kolla/config_files"
# The directory to store the config files on the destination node
node_config_directory: "/etc/kolla"

###################
# Kolla options
###################
# Valid options are [ COPY_ONCE, COPY_ALWAYS ]
config_strategy: "COPY_ALWAYS"

# Valid options are [ centos, fedora, oraclelinux, ubuntu ]
kolla_base_distro: "centos"
# Valid options are [ binary, source ]
kolla_install_type: "binary"

kolla_internal_vip_address: "{{ kolla_internal_address }}"
kolla_internal_fqdn: "{{ kolla_internal_vip_address }}"
kolla_external_vip_address: "{{ kolla_internal_vip_address }}"
kolla_external_fqdn: "{{ kolla_internal_fqdn if kolla_external_vip_address == kolla_internal_vip_address else kolla_external_vip_address }}"

kolla_enable_sanity_checks: "no"

kolla_enable_sanity_keystone: "{{ kolla_enable_sanity_checks }}"
kolla_enable_sanity_glance: "{{ kolla_enable_sanity_checks }}"
kolla_enable_sanity_cinder: "{{ kolla_enable_sanity_checks }}"
kolla_enable_sanity_swift: "{{ kolla_enable_sanity_checks }}"


####################
# Docker options
####################
docker_registry_email:
docker_registry: "10.21.0.55:5555"
docker_namespace: "chinac"
docker_registry_username:
docker_registry_password:

# Valid options are [ never, on-failure, always ]
docker_restart_policy: "always"

# '0' means unlimited retries
docker_restart_policy_retry: "10"

# Common options used throughout docker
docker_common_options:
    auth_email: "{{ docker_registry_email }}"
    auth_password: "{{ docker_registry_password }}"
    auth_registry: "{{ docker_registry }}"
    auth_username: "{{ docker_registry_username }}"
    environment:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
    restart_policy: "{{ docker_restart_policy }}"
    restart_retries: "{{ docker_restart_policy_retry }}"

####################
# OpenStack options
####################
openstack_release: "2.0.3"
openstack_logging_debug: "False"

openstack_region_name: "RegionOne"
enable_central_logging: "no"

# Optionally allow Kolla to set sysctl values
set_sysctl: "yes"

###################
# Ceph options
###################
enable_ceph: "yes"
enable_ceph_rgw: "no"
ceph_cluster_fsid: "2057e1dc-dea4-48f4-af8b-5b53cd5cd78d"
rgw_port: "6780"
# Ceph can be setup with a caching to improve performance. To use the cache you
# must provide separate disks than those for the OSDs
ceph_enable_cache: "no"
# Valid options are [ forward, none, writeback ]
ceph_cache_mode: "writeback"

# Valid options are [ ext4, btrfs, xfs ]
ceph_osd_filesystem: "xfs"

# These are /etc/fstab options. Comma seperated, no spaces (see fstab(8))
ceph_osd_mount_options: "defaults,noatime"

# A requirement for using the erasure-coded pools is you must setup a cache tier
# Valid options are [ erasure, replicated ]
ceph_pool_type: "replicated"

ceph_erasure_profile: "k=4 m=2 ruleset-failure-domain=host"
ceph_rule: "default host {{ 'indep' if ceph_pool_type == 'erasure' else 'firstn' }}"
ceph_cache_rule: "cache host firstn"

network_interface: "eth0"
api_interface: "{{ network_interface }}"
storage_interface: "{{ network_interface }}"
