---

- name: ungzip ceph-base.tar.gz
  unarchive:
    src: ceph-base.tar.gz
    dest: /tmp/
    copy: yes

- name: change registry
  shell: sed -i 's/REGISTRY/{{ docker_registry }}/g' /tmp/ceph-base/Dockerfile

- name: change namespace
  shell: sed -i 's/NAMESPACE/{{ docker_namespace }}/g' /tmp/ceph-base/Dockerfile

- name: change tag
  shell: sed -i 's/TAG/centos-binary-base/g' /tmp/ceph-base/Dockerfile

- name: change version
  shell: sed -i 's/VERSION/{{ openstack_release }}/g' /tmp/ceph-base/Dockerfile

- name: docker build ceph-base
  shell: docker build /tmp/ceph-base -t  {{ docker_registry }}/{{ docker_namespace }}/centos-binary-ceph-base:{{ openstack_release }}

- name: push ceph-base to registry
  shell: docker push {{ docker_registry }}/{{ docker_namespace }}/centos-binary-ceph-base:{{ openstack_release }}

