---

- name: ungzip ceph-osd.tar.gz
  unarchive:
    src: ceph-osd.tar.gz
    dest: /tmp/
    copy: yes

- name: change registry
  shell: sed -i 's/REGISTRY/{{ docker_registry }}/g' /tmp/ceph-osd/Dockerfile

- name: change namespace
  shell: sed -i 's/NAMESPACE/{{ docker_namespace }}/g' /tmp/ceph-osd/Dockerfile

- name: change tag
  shell: sed -i 's/TAG/centos-binary-ceph-base/g' /tmp/ceph-osd/Dockerfile

- name: change version
  shell: sed -i 's/VERSION/{{ openstack_release }}/g' /tmp/ceph-osd/Dockerfile

- name: docker build ceph-osd
  shell: docker build /tmp/ceph-osd -t  {{ docker_registry }}/{{ docker_namespace }}/centos-binary-ceph-osd:{{ openstack_release }}

- name: push ceph-osd to registry
  shell: docker push {{ docker_registry }}/{{ docker_namespace }}/centos-binary-ceph-osd:{{ openstack_release }}
